/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EmploiDuTemps;

import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;
import scolarité.Module;
import Dates.Annee;
import controlleur.Controlleur;
import java.util.Observable;
import java.util.Observer;
import javax.swing.table.TableModel;

/**
 *
 * @author Elmouatassim
 */
public class Tab extends javax.swing.JFrame implements Observer {
    public Monmodel model;
   Annee une_annee;
    
    /**
     * Creates new form Tab
     */
    public Tab() {
        System.out.println("on rentre dans le constructeur sans parametre TAB");
        model = new Monmodel();
    
        initComponents();
    }
    public Tab(Annee une_annee) {
        System.out.println("on rentre dans le constructeur avec parametre TAB");
        this.une_annee=une_annee;
        model = new Monmodel();
        une_annee.addObserver(this);
        this.setVisible(true);
    
        initComponents();
    }
    @Override
    public void update(Observable o, Object o1) {
    
    }
    public class Monmodel extends AbstractTableModel{
   
        public Monmodel(){
        
        }

        @Override
        public int getRowCount() {
            return 2;
        }

        @Override
        public int getColumnCount() {
            return 7;
        }

        @Override
        public Object getValueAt(int i, int i1) {
         /** ici j'ai penser a mettre le nom d'un module pour l'identifier dans le planning dans la table
          * 
         */
        return null;
        }
        @Override
        public String getColumnName(int col){ 
        System.out.println("On rentre dans le column");
       /** switch(col){
            case 0 :
                return null;
               
            case 1 : 
                return "mardi";
                
            case 2 : 
                return "mercredi";
                
            case 3 : 
                return "jeudi";
                
            case 4 : 
                return "vendredi";
                
            case 5 : 
                return "samedi";
            
            case 6 : 
                return "dimanche";
            
            
        }
        return null;**/
        for(col = 0; col <=une_annee.semaine.size(); col++){
            
        System.out.println("on rentre dans le for");
            return une_annee.a(col)+une_annee.c(col)+une_annee.b(col);
            
        }
            return null;
    }
        
    }
    public boolean isCellEditable(int row, int column){
        return false;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        controlleur1 = new controlleur.Controlleur(this.une_annee);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable2.setModel(model);
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);
        getContentPane().add(controlleur1, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
       /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            new Tab().setVisible(true);
            
            
              }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controlleur.Controlleur controlleur1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

}